spring:
  application:
    name: config-server
  cloud:
    config:
      label: master
      server:
        git:
#          uri: git@github.com:zyy13579/spring_cloud_demo.git
#          uri: https://github.com/zyy13579/spring_cloud_demo.git
#          search-paths: spring_cloud_demo/config_file
          uri: git@gitee.com:z_y_y/spring_cloud_config.git
          search-paths: spring_cloud_config
server:
  port: 8888
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
