eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: service-provider
  cloud:
    config:
      label: master
      profile: dev
#      uri: http://localhost:8888/
      discovery:
        enabled: true
        service-id: config-server
  rabbitmq:
    host: localhost
    port: 5672
    username: scadmin
    password: 123456

management:
  endpoints:
    web:
      exposure:
        include: ["health","info","refresh"]
#        include: "*"

server:
  port: 8081